server.port=8899
springwolf.docket.base-package=de.uol.swp.server
springwolf.docket.info.title=SWP
springwolf.docket.info.version=1.0.0
springwolf.docket.servers.stomp.protocol=stomp
springwolf.docket.servers.stomp.host=localhost:${server.port}/ws
