logging.level.root=DEBUG
logging.level.de.uol.swp=DEBUG
logging.level.sun.rmi=INFO
logging.level.javax.management.remote.rmi=INFO
logging.level.org.springframework=INFO
logging.level.io.github.springwolf=INFO
logging.level.io.swagger.v3=INFO
