package de.uol.swp.client;

import de.uol.swp.client.api.DefaultApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * This class provides basic configuration for the client.
 *
 * @author Tilman Holube
 * @since 2025-03-17
 */
@Configuration
public class ClientConfig {

    /**
     * Creates a new instance of the DefaultApi class.
     * This instance is used to communicate with the server.
     * <p>
     * The DefaultApi class is generated by the OpenAPI Generator.
     *
     * @return A new instance of the DefaultApi class
     * @author Tilman Holube
     * @see DefaultApi
     * @since 2025-03-17
     */
    @Bean
    public DefaultApi apiClient() {
        return new DefaultApi();
    }

}
